### PR TITLE
Restaurant Page Project#3

### PR DESCRIPTION
**Pull request by mcastorena0316**
Hello. 

This is my first draft of the Restaurant Page's project using Javascript. In this branch I:

- Create a page with Javascript that contains 4 sections: Main Section, Menu, Location, and Contact.
- Use modules to connect each section with index.js
- Use Webpack for file structuring.

Thanks!

### CODE REVIEW

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello @mcastorena0316 
Everything is OK except one requirement.
It asked to **It appends HTML elements to the `<div>` with `id=content` when the page is loaded (Use document.createElement and document.appendChild)** read it [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/append_requirement.png)
Which is not what you did. You put everything inside a `div#content` even the tab (which should be outside) and you used `display:none|flex` to hide|show the HTML part clicked on.

Please, make the change and submit a new code review request
Thanks

Mael FOSSO

**Comment by mcastorena0316** [comment]
Hi, I already realize the changes that were required so I'm asking for another review.

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello @mcastorena0316 
Thank you for the improvements you've done.
However, it's not what It was asked.

You should have at the end something like
```HTML
...
<div id="main">
  <header>
    ...
    <nav>Your tabs heere</nav>
  </header>
  <div id="content">
    <strong>THAT PART IS CHANGING EVERYTIME THE USER CLICK ON THE TAB</strong>
  </div>
</div>
...
```
Please, allow me to insist on **CHANGING**  not using `display: none` or `display: flex` but the old content is removing and replace by a new one. 
That is one of the [requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/append_requirement.png)

Kindly make the changes and submit a new code review request.
Thanks

Mael FOSSO

**Review by maelfosso — APPROVED** [review]
# Congratulations :clap:

You can merge it :+1:
Good luck with the next step :handshake:

Mael FOSSO

**Pull request merged**
